### ISSUE TITLE
Theme demo broken on Hugo Themes Showcase 

### ISSUE THREAD

**Issue by onedrawingperday** [gkmngrgn/hugo-alageek-theme#13]
Hello @gkmngrgn 

Currently your theme's demo does not generate as mentioned in https://github.com/gohugoio/hugoThemes/issues/669#issuecomment-518648215

To fix you need to change [line 8](https://github.com/gkmngrgn/hugo-alageek-theme/blob/master/theme.toml#L8) of `theme.toml` to: `min_version = "0.40"`

The `min_version` needs to be a string.

Feel free to close this issue once you do the above

Also note that once gohugoio/hugoThemes#668 is addressed you will need to keep an eye on whether the alaGeek theme demo generates on the Hugo website.

We are a very small team and we just cannot keep up opening issues in the various theme repositories. Whenever a theme demo breaks and remains broken then at some point it will be removed from the list without prior warning.

Thank you.

cc: @digitalcraftsman

**Comment by gkmngrgn** [comment]
Hi @onedrawingperday,

Can it be a different problem here? Because it's already a string. I checked if the version is valid or not but seems Hugo has a version **0.40**.

I looked at the error output and it says a different version:

```
11:27:21 AM:  ==== PROCESSING  hugo-alageek-theme  ======
11:27:21 AM: Building site for theme hugo-alageek-theme using default content to ../themeSite/static/theme/hugo-alageek-theme/
11:27:21 AM: Error: failed to read module config for "hugo-alageek-theme" in "/opt/build/repo/hugo-alageek-theme/theme.toml": unmarshal failed: Near line 8 (last key parsed 'min_version'): Invalid float value: "0.40.3"
11:27:21 AM: FAILED to create exampleSite for hugo-alageek-theme
```

I subscribed to the main issue. If you generate a new report and the problem still exists, I'll fix the problem as soon as possible. Thank you for letting me know.

**Comment by onedrawingperday** [comment]
Hello @gkmngrgn 

The ERROR report that was generated yesterday in the Hugo themes deploy was due to the fact that your latest commit https://github.com/gkmngrgn/hugo-alageek-theme/commit/899df0d61799a77dc60ed90ace61223b51ee869a#diff-55ff88866611c09606bf5330713a9987R8 wasn't used. The ERROR was due to the fact that before this commit the `min_version` was entered as 0.40.3 without quotes.

Since the themes were updated by @digitalcraftsman yesterday your theme's demo generates.

However note that the`min_version` as you have entered it now `"0.40" is not a valid semver version.

Since version 0.56.0 Hugo [uses semver versioned modules](https://github.com/gohugoio/hugo/blame/b4827fbb144573263371377e5b39be1fe1fa1466/docs/content/en/news/0.56.0-relnotes/index.md#L19) also see the relevant [issue](https://github.com/gohugoio/hugo/issues/5639)

Please change the `min_version` to `"0.40.0"`

Also now there a console warning when I test your theme:

```
 ==== PROCESSING  hugo-alageek-theme  ====== 
Building site for theme hugo-alageek-theme using default content to ../themeSite/static/theme/hugo-alageek-theme/
WARN 2019/08/07 06:41:10 Page's .RSSLink is deprecated and will be removed in a future release. Use the Output Format's link, e.g. something like: 
    {{ with .OutputFormats.Get "RSS" }}{{ .RelPermalink }}{{ end }}
```
The message is self-explanatory so please follow the instructions to remove the warning.

Once you do the above feel free to close this issue.

Thank you.

**Comment by gkmngrgn** [comment]
@onedrawingperday thank you for the feedback, I follow the next report.

**Comment by onedrawingperday** [comment]
Thank for the fixes.
