### ISSUE TITLE
How to enable pagination?

### ISSUE THREAD

**Issue by gaurs** [gkmngrgn/hugo-alageek-theme#16]
Hi Görgen,

Can you please suggest how do I get the pagination working on the blog page when the number of posts grows ?

**Comment by gkmngrgn** [comment]
Hi, Gaurs,

Thanks for the feedback. With my last commit, the theme considers Hugo's default "paginate" variable anymore. The default paginate value is 10 but it's possible to change it on your config file.

Here you can find more information about the pagination:
https://gohugo.io/templates/pagination/

![image](https://user-images.githubusercontent.com/72323/64914131-3bf6e280-d74d-11e9-94ca-9f402e0ec8a7.png)
