### ISSUE TITLE
How to configure the theme by default using the `dark` mode?

### ISSUE THREAD

**Issue by bangau1** [gkmngrgn/hugo-alageek-theme#19]
Hi, thank you for making and share this theme. I am trying to use this theme for my blog and wondering how I can set the default theme to use the dark mode?

**Comment by gkmngrgn** [comment]
@bangau1 Hi, the dark theme is working only if you activate dark mode on your operating system. All three popular operating systems and web browsers support this personalization anymore.

Currently, it's not possible to activate the dark theme in OS light mode. Technically it's possible to make configurable from Hugo config file. If you need it, I'll look at the topic this Sunday.

Maybe you can help me?

**Comment by gkmngrgn** [comment]
I decided not to do this issue because of a lack of time, but the theme is already easy-editable. you will just copy `static/css/main.css` and `static/css/highlight.css` files and edit however you want. You can replace the color definitions with dark-mode specific lines.
