### ISSUE TITLE
dark-mode enable

### ISSUE THREAD

**Issue by jerognlz** [gkmngrgn/hugo-alageek-theme#20]
How do you active the dark mode of the image ? 

i don't see the option in the documentation. 

Thanks!

**Comment by RealOrangeOne** [comment]
This is automatically derived from the browser using https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme.

src: https://github.com/gkmngrgn/hugo-alageek-theme/blob/0c88ee02a5b5981fa1aab5efcda221cc263e4c9f/static/css/main.css#L24

**Comment by gkmngrgn** [comment]
added a simple documentation about dark-mode [here](https://github.com/gkmngrgn/hugo-alageek-theme#how-dark-mode-works).
