### ISSUE TITLE
mathjax version needs to be updated

### ISSUE THREAD

**Issue by pmeckoni** [gkmngrgn/hugo-alageek-theme#22]
Mathjax is no longer working since it is related to version 2.7.5. 

After struggling for a long time, I finally got it to work, after replacing to version 2.7.7 of Mathjax.
Please update it in `baseof.html`

**Comment by gkmngrgn** [comment]
@pmeckoni, thanks for the issue. I did a bulk update (including bootstrap v5). Maybe you want to give it a try.
I'm closing the issue, for now. If you have another feedback about mathjax, comment here, I will reopen.

**Comment by pmeckoni** [comment]
I see you upgraded mathjax to always reflect the latest version of mathjax3. This is excellent.
Thanks.
