### ISSUE TITLE
Help with setting up the theme

### ISSUE THREAD

**Issue by vinitkumar** [gkmngrgn/hugo-alageek-theme#23]
Hi @gkmngrgn, thanks for creating this theme. I am a newbie in Hugo, so please bear with me if the issue is too trivial.

I am trying to port my website from gatsby to Hugo and found your theme.

Furthermore, I wanted to set it like you did, but the issue is I can't get it to look as the same as you have.

Here is an PR for the same.

I want two things from the theme:

- home page with some intro and blog links in the bottom.

Somehow, the config.toml doesn't work properly to show the links in the project.

https://github.com/vinitkumar/vinitkumar.me/pull/61/files#diff-28043ff911f28a5cb5742f7638363546311225a63eabc365af5356c70d4deb77

Would really appreciate some advice, and thanks for taking the time.

**Comment by vinitkumar** [comment]
Any help would be highly appreciated.

**Comment by gkmngrgn** [comment]
@vinitkumar sorry for to delay. Indeed I don't use a specific thing that doesn't exist in the theme. maybe that would be a good start to compare the config first:

https://gist.github.com/gkmngrgn/c5bcdb828e1ddb422768b66eb1374d7a

**Comment by niladridutt** [comment]
Hey @gkmngrgn, 
Thanks for making this awesome theme. Can you post a gist of your homepage (_index.md) as well? What font are you using and where do I need to make this change?
