### ISSUE TITLE
Any demo for how to set up the website?

### ISSUE THREAD

**Issue by hrmck** [gkmngrgn/hugo-alageek-theme#24]
I was trying to add paragraphs in the homepage using markdown.

I tried to put home.md under the content root folder (named `content-en`) but nothing is shown.
Attaching the config.toml here.
```
baseURL = 'http://example.org/'
builddrafts = false
canonifyurls = true
defaultContentLanguage = "en"
languageCode = "en"
layoutdir = "layouts"
publishdir = "public"
pluralizelisttitles = false
theme = "alageek"
title = 'test'
paginate = 20

[permalinks]
blog = "/blog/:year/:month/:slug/"

[languages.en]
languageName = "English"
contentDir = "content-en"
weight = 10

[[languages.en.menu.primary]]
identifier = "github-profile"
name = "GITHUB"
url = "https://github.com/hrmck"
weight = 10

[params]
...
```

Will it be possible to have some sort of demo repo (or directory) to show where exactly the files should be put?

**Comment by gkmngrgn** [comment]
I added a demo config so you can find it in `exampleSite`.
