### ISSUE TITLE
disqus comments integeration.

### ISSUE THREAD

**Issue by gaurs** [gkmngrgn/hugo-alageek-theme#8]
Is it possible to integrate disqus comments in the theme ? 

The default `{{ template "_internal/disqus.html" . }}` is not working when written in `blog/single.html`

**Comment by gkmngrgn** [comment]
@gaurs thanks for the feature request! I'll integrate Disqus asap.

**Comment by gkmngrgn** [comment]
@gaurs, the version 1.2.0 is including Disqus support. Hugo disables Disqus integration in the local, so you need to deploy somewhere to see the form. For example:
https://gokmengorgen.net/en/blog/how-do-i-publish-my-articles/

Here you can see more information about the integration:
https://gohugo.io/templates/internal/#configure-disqus
